### ISSUE TITLE
Drop React

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail-localize#715]
While the initial plans were grandiose, they never came to fruition and the focus, requirements and direction have changed. This means the React side of things make maintenance harder than it needs to be.

We should switch to regular HTML with a sprinkle of AJAX (the edit a particular translation bit)

This will allow us to keep up with any Wagtail UI changes and focus on more important functionality and bug fixes

```[tasklist]
### Tasks
- [ ] Replace React UI with custom form and markup
- [ ] Implement inline (AJAX) saving for individual translation fields
- [ ] Drop React
- [ ] Follow-up automate release management
```

**Comment by lb-** [comment]
Just dropped into this repo and saw this, if you need something similar to HTMX's swap (for Ajax style behaviour).

Maybe check out the Swap controller - https://github.com/wagtail/wagtail/blob/main/client/src/controllers/SwapController.ts

Some others may come in handy also. 

- https://github.com/wagtail/wagtail/blob/main/client/src/controllers/SubmitController.ts - SubmitController - dynamically submitting a form. 
- https://github.com/wagtail/wagtail/blob/main/client/src/controllers/ActionController.ts - Action controller - create a temporary DOM form element and POST to it, along with a few dynamic actions around that space. 

May be a bit easier that rolling too much custom JS, just patch in to any DOM events as needed. Might be a good use case to se how the Stimulus controllers can be leveraged for plugins. 

I also understand if the desire is not to be tied to undocumented (yet) Wagtail internals.
